### ISSUE TITLE
Does not work with TeamCity 9

### ISSUE THREAD

**Issue by szakib** [timomeinen/team-piazza#56]
Please make it compatible with TeamCity 9.

**Comment by timt** [comment]
+1

**Comment by raymanoz** [comment]
+1

**Comment by timt** [comment]
OK for anyone who needs this I have patched it. 

If you want the patched version it can be downloaded from:

https://bintray.com/artifact/download/timt/generic/piazza-20150123190753.zip

I will submit a pull request for this fix

**Comment by timt** [comment]
Pull request submitted

**Comment by szakib** [comment]
@timt Works, thanks!

**Comment by npryce** [comment]
Is that PR #57?

**Comment by timt** [comment]
Yes

**Comment by elfadotonto** [comment]
+1

**Comment by timomeinen** [comment]
Thank you very much for your support. I created a new release, which is compatible with TeamCity 9.x.

Please find it at [github](https://github.com/timomeinen/team-piazza/releases/latest) or [bintray](https://bintray.com/timomeinen/maven/team-piazza/).
